# Copyright (c) 2025, Open Duck Mini Jetson Project.
# SPDX-License-Identifier: BSD-3-Clause

"""Articulation configuration for the Open Duck Mini v2 robot.

Defines the robot asset, initial standing pose, and actuator model using
BAM-identified Feetech STS3250 servo parameters.
"""

import os

from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg
import isaaclab.sim as sim_utils

# Path to the converted USD file (generated by scripts/convert_mjcf_to_usd.py).
# Using absolute path resolved at import time.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_USD_PATH = os.path.join(
    _REPO_ROOT, "mini_bdx", "robots", "open_duck_mini_v2", "usd", "open_duck_mini_v2.usd"
)

OPEN_DUCK_MINI_V2_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=_USD_PATH,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
    ),
    # Default standing pose from the MuJoCo model (robot_motors.xml).
    # These are the MJCF qpos values that produce a stable bipedal stance.
    # Joint names map to the MJCF joint definitions; the MJCF→USD converter
    # preserves these names and directions.
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.17),  # Spawn height matching MuJoCo base pos
        joint_pos={
            # Left leg
            "left_hip_yaw": 0.002,
            "left_hip_roll": 0.053,
            "left_hip_pitch": -0.63,
            "left_knee": 1.368,
            "left_ankle": -0.784,
            # Right leg
            "right_hip_yaw": -0.003,
            "right_hip_roll": -0.065,
            "right_hip_pitch": 0.635,
            "right_knee": 1.379,
            "right_ankle": -0.796,
            # Head and antennas (neutral)
            "neck_pitch": 0.0,
            "head_pitch": 0.0,
            "head_yaw": 0.0,
            "head_roll": 0.0,
            "left_antenna": 0.0,
            "right_antenna": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    # The MJCF converter creates two articulation roots in the USD:
    # /robot_motors/worldBody (empty) and
    # /robot_motors/trunk_assembly/trunk_assembly (the robot).
    # Point to the correct one to avoid ambiguity.
    #
    # This was "/base/base" until the PLANT-1 fix (2026-08-11) merged the
    # massless `base` wrapper into `trunk_assembly`, which is now the
    # articulation root. See docs/jetson-mod/known_issues.md#plant-1.
    articulation_root_prim_path="/trunk_assembly/trunk_assembly",
    # Use 90% of joint limits as soft limits for the joint_pos_limits reward
    soft_joint_pos_limit_factor=0.9,
    # Actuator model using BAM-identified Feetech STS3250 servo parameters.
    # Source: kscalelabs/sysid feetech/sts3250/params/id008-params/m1.json
    #   kp (stiffness): 45.53  — BAM id008 MuJoCo export
    #   kd (damping):   1.346  — BAM id008 MuJoCo export
    #   armature:       0.040  — BAM id008
    #   friction:       0.200  — BAM id008 frictionloss
    #   effort_limit:   8.716  — BAM id008 forcerange
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                ".*_hip_yaw", ".*_hip_roll", ".*_hip_pitch",
                ".*_knee", ".*_ankle",
            ],
            stiffness=45.53,
            damping=1.346,
            armature=0.040,
            friction=0.200,
            effort_limit_sim=8.716,
        ),
        "head": ImplicitActuatorCfg(
            joint_names_expr=[
                "neck_pitch", "head_pitch", "head_yaw",
                "head_roll", ".*_antenna",
            ],
            stiffness=45.53,
            damping=1.346,
            armature=0.040,
            friction=0.200,
            effort_limit_sim=8.716,
        ),
    },
)
"""Configuration for the Open Duck Mini v2 bipedal robot with Jetson modification."""
