#!/usr/bin/env python3
"""Torque headroom from the S.2 reference traces — Task S.8.

Pure numpy over the recorded traces. No hardware, no GPU.

Percentiles alone cannot answer the question that matters, because **every
Feetech protection is duration-based**: over-current trips at >3.8 A held 2 s,
overload at >80 % of stall held 2 s, over-temperature at >70 degC. A 40 ms spike
and a 2 s sustained load are completely different risks and look identical in a
p99. So this also reports the longest CONSECUTIVE run above each threshold.

    python3 scripts/measure_torque_headroom.py

Writes docs/jetson-mod/sim2real/S8_torque_envelope.md.
"""

from __future__ import annotations

import json
import os

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIM2REAL = os.path.join(REPO, "docs", "jetson-mod", "sim2real")
CONTRACT = os.path.join(REPO, "jetson_runtime", "policy_contract.json")

CONTINUOUS_NM = 1.569      # Feetech "Rated Torque" 16 kg.cm @ 12 V
STALL_NM = 4.903           # datasheet stall 50 kg.cm @ 12 V, +/-10 %
OVERLOAD_NM = 3.923        # 80 % of stall — firmware overload trip, 2 s
PACK_CEILING_NM = 7.996    # BAM kt*V/R scaled to the 11.1 V pack (PLANT-5)
DT = 0.02


def longest_run(mask: np.ndarray) -> float:
    """Longest consecutive True run, in seconds."""
    best = cur = 0
    for v in mask:
        cur = cur + 1 if v else 0
        best = max(best, cur)
    return best * DT


def main() -> int:
    c = json.load(open(CONTRACT))
    order = c["joint_order"]
    rows, worst = {}, {}

    for name in ("fwd", "turn", "stand"):
        p = os.path.join(SIM2REAL, f"reference_trace_v7_{name}.npz")
        if not os.path.isfile(p):
            continue
        d = np.load(p, allow_pickle=True)
        app, comp = np.abs(d["applied_torque"]), np.abs(d["computed_torque"])
        per = {}
        for i, j in enumerate(order):
            a = app[:, i]
            per[j] = {
                "p50": float(np.percentile(a, 50)), "p95": float(np.percentile(a, 95)),
                "p99": float(np.percentile(a, 99)), "max": float(a.max()),
                "rms": float(np.sqrt((a**2).mean())),
                "comp_max": float(comp[:, i].max()),
                "frac_over_cont": float((a > CONTINUOUS_NM).mean()),
                "frac_over_stall": float((a > STALL_NM).mean()),
                "frac_over_pack": float((a > PACK_CEILING_NM).mean()),
                "run_over_cont_s": longest_run(a > CONTINUOUS_NM),
                "run_over_overload_s": longest_run(a > OVERLOAD_NM),
            }
        rows[name] = per
        worst[name] = max(per.items(), key=lambda kv: kv[1]["rms"])

    if not rows:
        print("no traces found — run scripts/record_reference_trace.py first")
        return 1

    lines = []
    w = lines.append
    w("# S.8 — servo torque headroom, measured from the reference traces\n")
    w("**Generated by `scripts/measure_torque_headroom.py`** over the S.2 traces "
      "of `v7_servo_safe`. Pure numpy; no hardware.\n")
    w("## The ceilings\n")
    w("| quantity | value | note |")
    w("|---|---|---|")
    w(f"| sim `effort_limit_sim` | **4.903 N·m** | the datasheet stall, since Task M0 fixed PLANT-5 |")
    w(f"| BAM `kt·V/R` at 11.1 V pack | {PACK_CEILING_NM} N·m | what the sim used to allow |")
    w(f"| datasheet stall (50 kg·cm @ 12 V) | {STALL_NM} N·m | ±10 % unit spread, printed |")
    w(f"| firmware **overload** trip | {OVERLOAD_NM} N·m | >80 % of stall held **2 s** |")
    w(f"| datasheet **rated** (16 kg·cm) | {CONTINUOUS_NM} N·m | Feetech says 'Rated', never 'continuous' |")
    w("")
    w("Firmware thresholds are **CITED** — Feetech ST-3250-C001 product "
      "specification, Edition A/0 (2024-01-16), §7-11 電子保護: over-current "
      "*'运行中电流大于3.8A并持续2s后，关闭输出'*, overload *'堵在大于堵转的80%并持续2S后进入保护'*, "
      "over-temperature *'大于70℃关闭扭矩输出'*. They are no longer UNVERIFIED.\n")

    for name, per in rows.items():
        jn, jv = worst[name]
        w(f"## Trace `{name}` — worst joint by RMS: `{jn}`\n")
        w("| joint | p50 | p95 | p99 | max | RMS | % > rated | longest run > rated | longest run > overload |")
        w("|---|---|---|---|---|---|---|---|---|")
        for j in order:
            v = per[j]
            w(f"| `{j}` | {v['p50']:.3f} | {v['p95']:.3f} | {v['p99']:.3f} | {v['max']:.3f} | "
              f"{v['rms']:.3f} | {v['frac_over_cont']*100:.1f} % | {v['run_over_cont_s']:.2f} s | "
              f"{v['run_over_overload_s']:.2f} s |")
        w("")

    # ---- the decision ---------------------------------------------------
    max_run_cont = max(v["run_over_cont_s"] for per in rows.values() for v in per.values())
    max_abs = max(v["max"] for per in rows.values() for v in per.values())
    max_run_ovl = max(v["run_over_overload_s"] for per in rows.values() for v in per.values())
    over_stall = [(n, j) for n, per in rows.items() for j, v in per.items() if v["frac_over_stall"] > 0]

    w("## Decision\n")
    w(f"- longest sustained run above the **rated** {CONTINUOUS_NM} N·m: **{max_run_cont:.2f} s**")
    w(f"- longest run above the **overload trip** {OVERLOAD_NM} N·m: **{max_run_ovl:.2f} s** "
      f"(the firmware needs **2.0 s** to trip)")
    w(f"- absolute maximum applied torque: **{max_abs:.3f} N·m** "
      f"(sim ceiling 4.903, datasheet stall {STALL_NM})")
    w("")
    accept = max_run_cont <= 0.5 and max_abs <= STALL_NM + 1e-6 and max_run_ovl < 2.0
    if accept:
        w("**ACCEPT — the policy is not leaning on torque the hardware lacks.**\n")
        w("No joint sustains more than 0.5 s above rated torque, nothing approaches "
          "the 2 s the firmware needs to trip either protection, and nothing exceeds "
          "the datasheet stall. The S.10 runtime limiter is the guard, and Task "
          "**S.8b** measures the real thermal behaviour on a bench servo.\n")
    else:
        w("**DO NOT ACCEPT on these numbers alone** — see the reasons above; fold "
          "an actuator-fidelity change into the next retrain.\n")

    w("## Three reasons these numbers under-state the risk\n")
    w("1. **`applied_torque` is Isaac Lab's Python approximation, not a PhysX "
      "measurement.** `ImplicitActuator.compute()` calculates "
      "`kp·(target−q) + kd·(0−qd)` and clips it to `effort_limit_sim`. It is also "
      "recomputed once per *physics* step inside the decimation loop, so a "
      "per-control-step read samples only the last of four substeps — brief peaks "
      "between substeps are invisible here.")
    w("2. **These traces are undisturbed.** No pushes, no wrench, no obstacles. "
      "The contact battery is where torque actually peaks.")
    w("3. **PLANT-6 is open**: dry friction is inactive during motion and BAM's "
      "viscous term is dropped, so simulated torque is not faithful motor torque.\n")
    w("## What this does NOT establish\n")
    w("Thermal behaviour. Feetech publishes **no thermal time constant and no "
      "duty-cycle curve**, so no amount of simulated torque can say whether the "
      "servo overheats. That is Task **S.8b** — one bench servo, measured.\n")

    dst = os.path.join(SIM2REAL, "S8_torque_envelope.md")
    open(dst, "w").write("\n".join(lines) + "\n")
    print("\n".join(lines[-14:]))
    print(f"\nwrote {os.path.relpath(dst, REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
